[package]
name = "sniffr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap = "0.9.1"
byteorder = "1.4.3"
serde_json = "1.0"
hex = "0.4.3"